permalink: /:categories/:year/:title/
markdown: kramdown
highlighter: pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Stupid Systems
description: "Concise Software for Small Problems."
email: andrew@stupidsystems.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://stupidsystems.com"

google_analytics: UA-11256323-1
# social footer
social:
  email:
    slug: star
    link: mailto:andrew@stupidsystems.com
  github:
    slug: github
    link: http://github.com/stupidsystems
  twitter:
    slug: twitter
    link: http://twitter.com/stupid_systems
  linkedin:
    slug: linkedin
    link: http://linkedin.com/in/andrewlb
